version: '3.3'
services:

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    env_file:
      - ./.env
  web:
    build:
      context: ../backend/foodgram
      dockerfile: Dockerfile
    restart: always
    volumes:
      - static_value:/app/static_backend/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static_backend/
      - media_value:/var/html/media/
    depends_on:
      - web
#    command: python3 manage.py runserver 0.0.0.8000
#    volumes:
#      - ./:/app/
volumes:
  postgres_data:
  static_value:
  media_value:
