# Generated by Django 4.0.6 on 2022-07-28 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredients',
            options={'verbose_name': 'Ingredient of a recipe', 'verbose_name_plural': 'Ingredients of recipes'},
        ),
    ]
