# Generated by Django 4.0.6 on 2022-08-02 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipeingredients_ingredient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredients',
            name='quantity',
        ),
        migrations.AddField(
            model_name='recipeingredients',
            name='amount',
            field=models.PositiveIntegerField(default=1, verbose_name='Amount'),
            preserve_default=False,
        ),
    ]
